services:
   app:
      build:
         context: .
         dockerfile: Dockerfile
         args:
            VITE_PUTER_WORKER_URL: ${VITE_PUTER_WORKER_URL}
      env_file:
         - .env
      ports:
         - '8767:3000'
      environment:
         - PORT=3000
      restart: unless-stopped
